package at.ennui.backend.offers.configuration;

public enum OfferCategories {
    CLIMBING, BOWLING, CINEMA, CART, BILLIARD, LASERTAG, SEGWAY, MUSEUM, PAINTBALL, TRAMPOLIN, CASINO, OPEN_AIR_POOL, INDOOR_POOL, THERMAL_BATH, HIGH_ROPE_COURSE, ICE_SKATE, ESCAPE_THE_ROOM,
    SKIING, WATER_SKIING, SWIMMING
}
